#这个文件是测试之前的东西
server:
  port: 9999

spring:
  application:
    name: gateWay-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心自动路由功能,
      routes: #路由
       - id: nacos-provider #没有固定要求, 路由id, 但是要保证唯一. 建议配合服务名
         uri: lb://nacos-provider/
         predicates: #断言
           - Path=/hx/** #路径相匹配进行路由
           - Weight=group1, 2
           #- Query=id,.+ # 匹配请求参数，这里如果需要匹        ++配多个参数，可以写多个Query
           #- Method=GET,POST
           #- Host=**.hx.com
           #- Header=X-Request-Id,\d+
           #- Cookie=username,[a-z]+ #匹配Cookie的key和value
           #- After=2022-01-12T17:24:10.529+08:00[Asia/Shanghai]  在这个时间点会后可以访问
           #https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#the-before-route-predicate-factory 这里的gateway的英文说明书,
